export const DAYS_IN_WEEK = 7;
export const HOURS_IN_DAY = 24;
export const MINUTES_IN_HOUR = 60;
export const MINUTES_IN_DAY = HOURS_IN_DAY * MINUTES_IN_HOUR;
export const MINUTES_IN_WEEK = MINUTES_IN_DAY * DAYS_IN_WEEK;

export const FIVE_MINUTE_INTERVALS_IN_HOUR = MINUTES_IN_HOUR / 5;
export const FIVE_MINUTE_INTERVALS_IN_DAY = FIVE_MINUTE_INTERVALS_IN_HOUR * 24;
export const FIVE_MINUTE_INTERVALS_IN_WEEK = FIVE_MINUTE_INTERVALS_IN_DAY * 7;

export const MIN_TIMEBOX = 1;
export const MAX_TIMEBOX = (((FIVE_MINUTE_INTERVALS_IN_WEEK - 1) << 9) | FIVE_MINUTE_INTERVALS_IN_DAY);